version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  router-agent:
    build: 
      context: .
      dockerfile: agents/router_agent/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  technical-agent:
    build:
      context: .
      dockerfile: agents/technical_agent/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  account-agent:
    build:
      context: .
      dockerfile: agents/account_agent/Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  demo-app:
    build:
      context: .
      dockerfile: demo/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - router-agent
      - technical-agent
      - account-agent
